/**
 * R4 search-parameter registry — per resource type, the supported search params
 * (token | string | date | reference | uri) with the FHIRPath expression for that type.
 * Generated by scripts/generate-search-params.ts from the CC0 R4 Core SearchParameters.
 */
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

export interface SearchParamDef {
  type: string;
  expression: string;
  target?: string[]; // reference param target resource types (for chaining)
}

const registry: Record<string, Record<string, SearchParamDef>> = JSON.parse(
  readFileSync(fileURLToPath(new URL("./r4-search-params.json", import.meta.url)), "utf8"),
);

/** Supported search params for a resource type ({} if none/unknown). */
export function searchParamsFor(resourceType: string): Record<string, SearchParamDef> {
  return registry[resourceType] ?? {};
}

/** A single param definition, or undefined if not supported for that type. */
export function searchParam(resourceType: string, code: string): SearchParamDef | undefined {
  return registry[resourceType]?.[code];
}
