/**
 * R4 search-parameter registry — per resource type, the supported search params
 * (token | string | date | reference | uri) with the FHIRPath expression for that type.
 * Generated by scripts/generate-search-params.ts from the CC0 R4 Core SearchParameters.
 */
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

export interface SearchParamDef {
  type: string;
  expression: string;
  target?: string[]; // reference param target resource types (for chaining)
  /** Composite params only: the two component sub-params (restricted expression grammar —
   * `prop` / `prop.as(Type)` relative to `expression`'s base elements). */
  components?: Array<{ expression: string; type: "token" | "quantity" | "string" | "date" }>;
}

const registry: Record<string, Record<string, SearchParamDef>> = JSON.parse(
  readFileSync(fileURLToPath(new URL("./r4-search-params.json", import.meta.url)), "utf8"),
);

// Additive IG params (e.g. CARIN BB EOB `type`/`service-date`) — imported after the core registry so
// core is the base and profile params extend it. Kept separate so the generated core JSON stays pure.
import { PROFILE_SEARCH_PARAMS } from "./profile-search-params.js";
import { COMPOSITE_SEARCH_PARAMS } from "./composite-search-params.js";

/** Supported search params for a resource type (core + additive profile/composite params;
 * {} if none/unknown). Composites live in their own registry because the codegen drops
 * type `composite` from the core JSON. */
export function searchParamsFor(resourceType: string): Record<string, SearchParamDef> {
  const core = registry[resourceType];
  const profile = PROFILE_SEARCH_PARAMS[resourceType];
  const composite = COMPOSITE_SEARCH_PARAMS[resourceType];
  if (!core && !profile && !composite) return {};
  return { ...(profile ?? {}), ...(composite ?? {}), ...(core ?? {}) }; // core last → core always wins
}

/** A single param definition, or undefined if not supported for that type. */
export function searchParam(resourceType: string, code: string): SearchParamDef | undefined {
  return registry[resourceType]?.[code]
    ?? COMPOSITE_SEARCH_PARAMS[resourceType]?.[code]
    ?? PROFILE_SEARCH_PARAMS[resourceType]?.[code];
}
